import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { redirect } from "next/navigation";
import Sidebar from "@/components/Sidebar";
import Link from "next/link";
import { Files, Plus, ScrollText } from "lucide-react";
import { Card } from "@/components/Card";

export default async function SummariesPage() {
    const session = await auth();

    if (!session) {
        redirect("/api/auth/signin");
    }

    const collections = await prisma.collection.findMany({
        where: {
            userId: session.user.id,
            summaries: { some: {} } // Only collections with summaries
        },
        include: {
            _count: { select: { summaries: true } },
            summaries: { take: 1, orderBy: { createdAt: 'desc' }, select: { title: true, createdAt: true } }
        },
        orderBy: { createdAt: 'desc' }
    });

    return (
        <div className="flex min-h-[calc(100vh-80px)]">
            <Sidebar />

            <main className="flex-1 p-4 md:p-8 overflow-y-auto">
                <div className="max-w-6xl mx-auto">
                    <header className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4">
                        <div>
                            <h1 className="text-3xl md:text-4xl font-bold text-gradient mb-2">Smart Summaries</h1>
                            <p className="opacity-60">Your concise study notes Generated by AI.</p>
                        </div>
                        <Link
                            href="/summary/new"
                            className="btn-primary flex items-center gap-2 shadow-lg shadow-purple-500/20"
                        >
                            <Plus size={20} /> New Summary
                        </Link>
                    </header>

                    {collections.length > 0 ? (
                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                            {collections.map((col) => (
                                <Card key={col.id} className="group cursor-pointer hover:border-[var(--secondary)] transition-colors">
                                    <div className="flex justify-between items-start mb-4">
                                        <div className="p-3 rounded-lg bg-[var(--secondary-glow)] text-[var(--secondary)]">
                                            <Files size={24} />
                                        </div>
                                        <span className="text-xs font-mono opacity-50 bg-[var(--card-border)] px-2 py-1 rounded">
                                            {new Date(col.createdAt).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' })}
                                        </span>
                                    </div>
                                    <h3 className="text-xl font-bold mb-2 group-hover:text-[var(--secondary)] transition-colors line-clamp-1">{col.name}</h3>

                                    {col.summaries[0] && (
                                        <div className="mb-4">
                                            <p className="text-sm opacity-60 line-clamp-2 italic">"{col.summaries[0].title}"</p>
                                        </div>
                                    )}

                                    <div className="flex items-center gap-2 text-sm opacity-60 mt-auto pt-4 border-t border-[var(--card-border)]">
                                        <ScrollText size={16} />
                                        <span>{col._count.summaries} summaries</span>
                                    </div>
                                </Card>
                            ))}
                        </div>
                    ) : (
                        <Card className="text-center py-20 border-dashed flex flex-col items-center justify-center" hoverEffect={false}>
                            <div className="p-4 rounded-full bg-[var(--card-border)] mb-4 opacity-50">
                                <Files size={40} />
                            </div>
                            <h3 className="text-xl font-bold mb-2">No summaries yet</h3>
                            <p className="opacity-60 max-w-sm mx-auto mb-6">Condense long texts into easy-to-digest summaries.</p>
                            <Link
                                href="/summary/new"
                                className="btn-primary inline-flex items-center gap-2"
                            >
                                <Plus size={18} /> Create First Summary
                            </Link>
                        </Card>
                    )}
                </div>
            </main>
        </div>
    );
}
